[package]
name = "rest2smtp"
version = "0.2.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.0-rc.3", default-features = false, features = ["json"] }
lettre = { version = "0.10.3", features = ["tokio1", "tokio1-native-tls"] }
