[package]
name = "rest2smtp"
version = "0.0.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", default-features = false, features = ["json"] }
lettre = { version = "0.11.14", features = ["tokio1", "tokio1-native-tls"] }